version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: ankur9718/zmcase2:latest
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - run:
         whoami             
      - run: 
         sudo apt-get update -y
      - run: 
         sudo apt-get install docker.io -y
      - run:
         sudo docker images                
   

workflows:
  my-custom-workflow:
    jobs:
       - my-job-name
