version: 2.1
jobs:
   build:
      docker:
         - image: ankur9718/zmcase2:latest
      steps:
         - run:
            whoami             
         - run:
            git clone https://github.com/Zimbra/zm-build.git 
            
                         
   

  