version: 2.1
jobs:
   build:
      docker:
         - image: ankur9718/zmcase2:latest
      steps:
         - checkout
        
         - run:
            ls             
         - run:
            git show --name-only e4a717390cae895c9a3a34bf934ab86b9b5066d8 | grep config.build
         - run:
            command: |
               if [ $? -eq 0 ]
               then
                 echo "config files changed"
               fi
