version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: ubuntu:18.04
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run:
         whoami             
      - run: 
         apt-get update -y
      - run: 
         apt-get install docker.io -y
      - run: 
         apt-get install sudo -y
      - run: 
         docker build -t zmbuildimg .

workflows:
  my-custom-workflow:
    jobs:
       - my-job-name
