version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: ankur9718/zmcase2:latest
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - run:
         docker run -it --name zmcontain ankur9718/zmcase2 /bin/bash             
      

workflows:
  my-custom-workflow:
    jobs:
       - my-job-name
