version: 2.1
jobs:
   build:
      docker:
         - image: ankur9718/zmcase2:latest
      steps:
         - run:
            whoami             
         - run: 
            docker run -it --name zmcont ankur9718/zmcase2 /bin/bash
                         
   

  