version: 2.1
jobs:
   build:
      docker:
         - image: ankur9718/zmcase2:latest
      steps:
         - checkout
        
         - run:
            ls             
         - run:
            git show --name-only ${CIRCLE_SHA1} | grep config.build
            if [ $? -eq 0 ]; 
            then 
              echo "Ankur Sharma" 
            fi